---
title: "Professional Applications of Data Science"
---

## OVERVIEW

This repository serves as a collaborative development environment for the University of Idaho's graduate certificate, Professional Applications of Data Science.  The repository and its associated website integrate the current state of the certificate's courses, marketing materials, and development plan.  

## CERTIFICATE SUMMARY

Basic data literacy and data science skills are becoming central to virtually every industry. Yet, limited opportunities exist to gain these skills without an advanced background in math and computer science. The [Graduate Certificate in Professional Applications of Data Science](Certificate/index.qmd) is designed to fill this growing workforce development need.  The certificate provides rigorous training in the foundations of data science and can be customized to each student's disciplinary needs and background. Students will learn how to think about, organize, analyze, and visualize data, and communicate data driven insights to diverse audiences. The curriculum is modular and flexible and emphasizes the use of data sets drawn from each student's individual discipline. 

A detailed description of the certificate can be found [here](Certificate/index.qmd)

### Curriculum

The 12 credit certificate requires the following courses:

#### INTR 509 Introduction to Applied Data Science (3 credits)

Students are provided a foundation for "thinking with data" through the introduction of computational, statistical, and data literacy skills. This includes the selection, collection, cleaning, management, descriptive analysis, and exploratory analysis of a dataset unique to their professional interests using modern computing languages.

#### [BCB 520 Data Visualization](https://professorpolymorphic.github.io/RobisonWebSite/BCB520/) (3 credits)

This course covers the conceptual foundations of data visualization and design. Students will learn how visualization design choices related to marks and channels, color, and spatial arrangement interact with the human perceptual system. The course considers tabular, network, and spatial data, and students will implement visualizations in R.

#### BCB 521 Communicating with Data (2 credits)

Students are taught writing and presentation skills to improve their communication of data-driven insights to specialist and lay audiences. The course emphasizes reproducible research practices, including literate programming (R Markdown) and version control (GitHub). Course content includes the conceptual foundations of communicating with data along with written and verbal communication assignments using data sets individualized to each student's interest. 

#### BCB 522 Data Science Portfolio (1 credit)

This course provides feedback, review, and approval of the student's online data science portfolio. This portfolio is intended to represent the body of work accumulated by the student over the course of the certificate. It should contain examples of novel data products (such as FAIR data sets), analyses, and visualizations. All elements of the portfolio will be hosted online (likely in a GitHub repository or professional website), be open source, and demonstrate best practices of literate programming and reproducible research. 

#### Data Science Elective (3 credits:

The certificate allows each student to customize their training by choosing a 3-credit graduate elective.

For students seeking foundational training who have not already taken Stat 431 or its equivalent, ***we recommend Stat 431 or a 3-credit graduate level disciplinary research methods course***.

For students seeking to add the certificate to an existing degree at UI, or students who already have some advanced technical training, [many additional electives are possible](Certificate/index.qmd####Electives). 


## TASKS

### [Marketing Plan](Marketing.qmd)

### [Online Course Development](Online.qmd)

### Certificate Assessment

### Elective Integration

### [Resources and Opportunities](Resources.qmd)


